name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Preparing build environment
        run:
          docker build -q -t confd_builder -f Dockerfile.build.alpine .
      - name: Build confd
        run: |
          VERSION=`egrep -o '[0-9]+\.[0-9a-z.\-]+' version.go`
          docker run --rm -v ${PWD}:/app -e "GOOS=linux" -e "GOARCH=amd64" -e "CGO_ENABLED=0" confd_builder \
            go build -ldflags="-s -w -X main.GitSHA=${GIT_SHA}" -o bin/confd-${VERSION}-linux-amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/confd-0.17.0-dev-linux-amd64
