name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Preparing build environment
        run:
          docker build -q -t confd_builder -f Dockerfile.build.alpine .
      - name: Build confd
        run: |
          VERSION=`egrep -o '[0-9]+\.[0-9a-z.\-]+' version.go`
          docker run --rm -v ${PWD}:/app -e "GOOS=linux" -e "GOARCH=arm64" -e "CGO_ENABLED=0" confd_builder \
            go build -ldflags="-s -w -X main.GitSHA=${GIT_SHA}" -o bin/confd-${VERSION}-linux-arm64
      - name: test
        run: |
          ls -l
          ls -l bin
      - name: Upload binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/confd-0.17.0-dev-linux-arm64
          asset_name: confd-0.17.0-dev-linux-arm64
