name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.10
        uses: actions/setup-go@v1
        with:
          go-version: 1.10

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go mod init tmp
          go mod vendor
          go mod tidy
          make build
